{% set name = "iprpy-data" %}
{% set version = "2021.2.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lmhale99/potentials-library/archive/efe598d99f1a2801f1561988cf28d7d5de56c4d2.tar.gz
  sha256: 137ba8d7ad56940b9db14a992cfb91c8391f644da76cd21eefd68bdb7e1e72d0

build:
  number: 1
  noarch: python
  run_exports:
    - {{ pin_subpackage('iprpy-data', max_pin='x.x.x') }}

requirements:
  build:
    - potentials
    - pandas
    - edn_format
    - openkim-models
    - kimpy
    - mendeleev
  host:
    - python
  run:

test:
  commands:
    - test -f ${PREFIX}/share/iprpy/potentials_lammps.csv  # [unix]

about:
  home: https://github.com/usnistgov/iprPy
  license: OTHER
  license_family: OTHER
  license_file: LICENSE.TXT
  summary: 'NIST Interatomic Potential Repository property calculation tools'

  description: |
    The iprPy framework is a collection of tools and resources supporting 
    the design of scientific calculations that are open source with minimum 
    barriers for usage, have transparent methodologies supporting knowledge 
    transfer and education, produce results that are both human and machine 
    readable, allow investigations into method and parameter sensitivity, 
    and can be integrated into workflows
  doc_url: https://www.ctcms.nist.gov/potentials/iprPy/
  dev_url: https://github.com/usnistgov/iprPy

extra:
  recipe-maintainers:
    - jan-janssen
