{% set name = "iprpy-data" %}
{% set version = "2021.12.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lmhale99/potentials-library/archive/refs/tags/{{ version|replace('.', '-') }}.tar.gz
  sha256: 016698f75d1d3ddaf9efe24d68b7ee6743aca4a52c5f1f46d2cdf8d72accff7f

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage('iprpy-data', max_pin='x.x.x') }}

requirements:
  build:
    - potentials =0.2.8
    - pandas
    - edn_format
    - openkim-models
    - kimpy =1.0.0
    - mendeleev
  host:
    - python >=3.7
  run:
    - python >=3.7

test:
  commands:
    - test -f ${PREFIX}/share/iprpy/potentials_lammps.csv  # [unix]

about:
  home: https://github.com/usnistgov/iprPy
  license: OTHER
  license_family: OTHER
  license_file: LICENSE.TXT
  summary: 'NIST Interatomic Potential Repository property calculation tools'

  description: |
    The iprPy framework is a collection of tools and resources supporting 
    the design of scientific calculations that are open source with minimum 
    barriers for usage, have transparent methodologies supporting knowledge 
    transfer and education, produce results that are both human and machine 
    readable, allow investigations into method and parameter sensitivity, 
    and can be integrated into workflows
  doc_url: https://www.ctcms.nist.gov/potentials/iprPy/
  dev_url: https://github.com/usnistgov/iprPy

extra:
  recipe-maintainers:
    - jan-janssen
